In [ ]:
#1
class PlayerEarning:
  def __init__(self,name):
    self.name=name
    self.bonus=0
    self.after_bonus=0
  def calculateTotal(self,e,goal=None):
    self.e=e
    self.goal=goal
    if self.goal==None:
      self.bonus=0
      self.after_bonus=self.e+self.bonus
    else:
      if self.goal > 30:
        self.bonus=int((5/100) * self.e + 10000)
        self.after_bonus=int(self.e+self.bonus)
      else:
        self.bonus=int((5/100) * self.e)
        self.after_bonus=self.e+self.bonus
  def printDetails(self):
      if self.bonus == 0:
        print(f'Player Name:{self.name}')
        print(f'Player Season Earning without bonus:{self.e}')
        print(f'Bonus:{self.bonus}')
        print(f'Player Season Earning After Bonus:{self.after_bonus}')
      else:
        print(f'Player Name:{self.name}')
        print(f'Player Season Earning without bonus:{self.e}')
        print(f'Bonus:{self.bonus}')
        print(f'Player Season Earning After Bonus:{self.after_bonus}')

print("**********************")
player1 = PlayerEarning('Buffon')
player1.calculateTotal(250000)
player1.printDetails()

print("\n**********************")
player2 = PlayerEarning('Dybala')
player2.calculateTotal(250000, 31)
player2.printDetails()

print("\n**********************")
player3 = PlayerEarning('Cuadrado')
player3.calculateTotal(250000, 20)
player3.printDetails()

**********************
Player Name:Buffon
Player Season Earning without bonus:250000
Bonus:0
Player Season Earning After Bonus:250000

**********************
Player Name:Dybala
Player Season Earning without bonus:250000
Bonus:22500
Player Season Earning After Bonus:272500

**********************
Player Name:Cuadrado
Player Season Earning without bonus:250000
Bonus:12500
Player Season Earning After Bonus:262500

In [ ]:
#2
class myList:
   def __init__(self,*args):
     self.args=args
     self.lst=[]
     for i in self.args:
       self.lst.append(i)
     print(self.lst)

   def sum(self):
     print(f'Sum:{sum(self.lst)}')

   def merge(self,*arg):
     self.arg=arg
     self.lst += [i for i in arg]

   def average(self):
     print(f'Average:{sum(self.lst)/len(self.lst)}')
l1 =  myList(2,3,4,5,6) #you might need a list inside your class to store the values
l1.sum()
l1.merge(4,5,9)
l1.sum()
l1.average()
print('-----------------------------')
l2 =  myList()
l2.average()
l2.merge(1,2,4,8)
l2.sum()

[2, 3, 4, 5, 6]
Sum:20
Sum:38
Average:4.75
-----------------------------
[]

ZeroDivisionError: ignored

In [ ]:
#3
class Bird:
  def __init__(self,name,typ=None):
    self.name=name
    self.typ=typ
    self.t='Flightless Birds'
  def fly(self):
      if self.typ==True:
        print(f'{self.name} can fly')

      else:
        print(f"{self.name} can not fly")

  def setType(self,t):
    self.t=t

  def printDetail(self):
    print(f'Name:{self.name}\nType:{self.t}')

ostrich = Bird('Ostrich')
duck = Bird("Duck", True)
owl = Bird('Owl', True)
print('###########################')
ostrich.fly()
duck.fly()
owl.fly()
duck.setType('Water Birds')
owl.setType('Birds of Prey')
print('=========================')
ostrich.printDetail()
print('=========================')
duck.printDetail()
print('=========================')
owl.printDetail()

###########################
Ostrich can not fly
Duck can fly
Owl can fly
=========================
Name:Ostrich
Type:Flightless Birds
=========================
Name:Duck
Type:Water Birds
=========================
Name:Owl
Type:Birds of Prey

In [ ]:
#4
class Account:
  count=0
  def __init__(self,name,age,occupation,amount):
    self.name=name
    self.age=age
    self.occupation=occupation
    self.amount=amount
    self.x=0
    Account.count += 1

  def addMoney(self,money):
    self.amount += money

  def printDetails(self):
       print(f"Name:{self.name}\nAge:{self.age}\nOccupation:{self.occupation}\nTotal Amount:{self.amount}")


  def withdrawMoney(self,withdraw):
    self.withdraw=withdraw
    if self.amount >= withdraw:
     self.amount -= withdraw
    pass

print('No of account holders:', Account.count)
print("=========================")
p1 = Account("Abdul", 45, "Service Holder", 500000)
p1.addMoney(300000)
p1.printDetails()
print("=========================")
p2 = Account("Rahim", 55, "Businessman", 700000)
p2.withdrawMoney(700000)
p2.printDetails()
print("=========================")
p3 = Account("Ashraf", 62, "Govt. Officer", 200000)
p3.withdrawMoney(250000)
p3.printDetails()
print("=========================")
print('No of account holders:', Account.count)

No of account holders: 0
=========================
Name:Abdul
Age:45
Occupation:Service Holder
Total Amount:800000
=========================
Name:Rahim
Age:55
Occupation:Businessman
Total Amount:0
=========================
Name:Ashraf
Age:62
Occupation:Govt. Officer
Total Amount:200000
=========================
No of account holders: 3

In [ ]:
#5
s1 = Smartphone()
print("=================================")
s1.addFeature(“Display”, “6.1 inch”)
print("=================================")
s1.setName(“Samsung Note 20”)
s1.addFeature(“Display”, “6.1 inch”)
s1.printDetail()
print("=================================")
s2 = Smartphone(“Iphone 12 Pro”)
s2.addFeature(“Display”, “6.2 inch”)
s2.addFeature(“Ram”, “6 GB”)
print(=================================")
s2.printDetail()
s2.addFeature(“Display”, “Amoled panel”)
s2.addFeature(“Ram”, “DDR5”)
print("=================================")
s2.printDetail()
print("=================================")

In [ ]:
#6
class Student:
  total=0
  cse=0
  bba=0
  def __init__(self,name,dept):
    self.name=name
    self.dept=dept
    Student.total += 1
    print(f'Creating Student Number:{Student.total}')
    if self.dept == "CSE":
      Student.cse += 1
    else:
      Student.bba += 1
  def individualInfo(self):
    print(f'{self.name} is from {self.dept} department.')
    print(f"Serial of {self.name} among all students' is: {Student.total} ")
    print(f"Serial of {self.name} in {self.dept} department is:{Student.cse}")
  def totalInfo(self):
    print(f"Total Number of Student:{Student.total}")
    print(f"Total Number of CSE Student:{Student.cse}")
    print(f"Total Number of BBA Student:{Student.bba}")

s1 = Student("Naruto", "CSE")
print('----------------------')
s1.individualInfo()
print('#############################')
s1.totalInfo()
print('============================')

s2 = Student("Sakura", "BBA")
print('----------------------')
s2.individualInfo()
print('#############################')
s2.totalInfo()
print('============================')

s3 = Student("Shikamaru", "CSE")
print('----------------------')
s3.individualInfo()
print('#############################')
s3.totalInfo()
print('============================')

s4 = Student("Deidara", "BBA")
print('----------------------')
s4.individualInfo()
print('#############################')
s4.totalInfo()

Creating Student Number:1
----------------------
Naruto is from CSE department.
Serial of Naruto among all students' is: 1
Serial of Naruto in CSE department is:1
#############################
Total Number of Student:1
Total Number of CSE Student:1
Total Number of BBA Student:0
============================
Creating Student Number:2
----------------------
Sakura is from BBA department.
Serial of Sakura among all students' is: 2
Serial of Sakura in BBA department is:1
#############################
Total Number of Student:2
Total Number of CSE Student:1
Total Number of BBA Student:1
============================
Creating Student Number:3
----------------------
Shikamaru is from CSE department.
Serial of Shikamaru among all students' is: 3
Serial of Shikamaru in CSE department is:2
#############################
Total Number of Student:3
Total Number of CSE Student:2
Total Number of BBA Student:1
============================
Creating Student Number:4
----------------------
Deidara is from BBA department.
Serial of Deidara among all students' is: 4
Serial of Deidara in BBA department is:2
#############################
Total Number of Student:4
Total Number of CSE Student:2
Total Number of BBA Student:2

In [ ]:
#7
class book:
    def __init__(self, name):
        self.name = name
        self.genre='biography'
    def review(self):
         print('This book is just out of the world,mind-blowing!')

# Write your code here
class fiction(book):
  def __init__(self,name,genre):
    super().__init__(name)
    self.genre=genre
  def review(self):
    print(f"{self.name} which is a {self.genre} is just out of the world, mind-blowing!")

class nonfiction(book):
  def __init__(self,name):
    super().__init__(name)
  def review(self):
     print(f"{self.name} which is a {self.genre} is just out of the world, mind-blowing!")

b1 = fiction('The Shining','Psychological horror')
b2 = nonfiction('A Beautiful Mind')
b1.review()
print('=========================')
b2.review()
print('=========================')

The Shining which is a Psychological horror is just out of the world, mind-blowing!
=========================
A Beautiful Mind which is a biography is just out of the world, mind-blowing!
=========================

In [ ]:
#8
class Processor:
    def __init__(self, model, thread, core):
        self.model = model
        self.core = core
        self.thread = thread

    def getInfo(self):
        # return "Model:"+self.model+ "\nCores:"+str(self.core)+ "\nThreads:"+ str(self.thread)
        return "Model:"+self.model+ "\nCores:"+str(self.core)+ "\nThreads:"+ str(self.thread)

# Write your code here

class Intel(Processor):
  def __init__(self,model,core,thread,price):
    super().__init__(model,thread,core)
    self.price=price

  def getInfo(self):
    a=super().getInfo()
    print(a + f"\nPrice:{self.price}")

class AMD(Processor):
  def __init__(self,model,core,thread,price):
    super().__init__(model,thread,core)
    self.price=price

  def getInfo(self):
    a=super().getInfo()
    print(a + f"\nPrice:{self.price}")


p1 = Intel("Intel i5 10th Gen",6,12,17000)
p2 = AMD("Ryzen 5 3500X",6,6,13800)
p3 = AMD("Ryzen 5 3600",6,12,16900)
print('======================')
p1.getInfo()
print('======================')
p2.getInfo()
print('======================')
p3.getInfo()

======================
Model:Intel i5 10th Gen
Cores:6
Threads:12
Price:17000
======================
Model:Ryzen 5 3500X
Cores:6
Threads:6
Price:13800
======================
Model:Ryzen 5 3600
Cores:6
Threads:12
Price:16900

In [ ]:
#9
class Fruit:
    Total_order=0

    def __init__(self, Order_ID, weight):
        self.Order_ID=Order_ID
        self.weight=weight
        Fruit.Total_order=Fruit.Total_order+1

    def __str__(self):
        return self.Order_ID+", Weight: "+str(self.weight)

class Mango(Fruit):
    def __init__(self, Order_ID, weight,variety,price):
      super().__init__(Order_ID,weight)
      self.variety=variety
      self.price=price
      self.total_price=self.price*self.weight
    def __str__(self):
      a=super().__str__()
      return a +','+ f"Variety:{self.variety} \nTotal Price:{self.total_price} "
    def __add__(self,other):
      m=self.total_price+other.total_price
      return f"The total Price of the orders are:{m}"
class JackFruit(Fruit):
    def __init__(self, Order_ID, weight,price):
      super().__init__(Order_ID,weight)
      self.price=price
      self.total_price=self.price*self.weight
    def __str__(self):
      a=super().__str__()
      return a+','+f"Total Price:{self.total_price} "
    def __add__(self,other):
      j=self.total_price+other.total_price
      return f"The total Price of the orders are:{j}"
m1=Mango("Order Id 1", 5,"GopalVog",250)
print(m1)
m2=Mango("Order Id 2", 5,"HariVanga", 230)
print(m2)
j1=JackFruit("Order Id 3", 5,250)
print(j1)
j2=JackFruit("Order Id 4", 4,210)
print(j2)
print("Total number of Orders: "+str(Fruit.Total_order))
print("==================")
print(m1+m2)
print("==================")
print(j1+j2)

Order Id 1, Weight: 5,Variety:GopalVog
Total Price:1250
Order Id 2, Weight: 5,Variety:HariVanga
Total Price:1150
Order Id 3, Weight: 5,Total Price:1250
Order Id 4, Weight: 4,Total Price:840
Total number of Orders: 4
==================
The total Price of the orders are:2400
==================
The total Price of the orders are:2090

In [ ]:
#10

In [ ]:
#11
class Transport:
    total_traveller = 0

    def __init__(self, name, fare):
        self.name = name
        self.baseFare = fare

    def __str__(self):
        s =  "Name: "+self.name+", Base fare: "+str(self.baseFare)
        return s
class Bus(Transport):
  def __init__(self,name,fare):
    super().__init__(name,fare)
    print(f"Base-fare of {self.name} is {self.baseFare} Taka ")
  def addPassengerWithBags(self,*args):

t1 = Bus('Volvo', 950)
print("=================================")
# t1.addPassengerWithBags('David', 6,  'Mike', 1, 'Carol', 3)
# print("=================================")
# print(t1)
# print("=================================")
# t2 = Train(“Silk City”, 850)
# print("=================================")
# t2.addPassengerWithBags('Bob', 2, 'Simon', 4)
# print("=================================")
# print(t2)
# print("=================================")
# print('Total Passengers in Transport: ', Transport.total_traveller )

Base-fare of Volvo is 950 Taka
=================================

In [ ]:
#12
class AppleProduct:
  def __init__(self, name, model, base_price):
    self.name = name
    self.model = model
    self.base_price = base_price
  def companyInfo(self):
    st = ("Company Name: Apple\nFouder: Steve Jobs, Steve Wozniak, Ronald Wayne\nCurrent CEO: Tim Cook\nAddress: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States")
    return st
  def feature(self):
    st = (f"Name: {self.name}\nProduct Model: {self.model}\nHardware Quality: Excellent Hardwares\nGuarantee/ Warranty: Apple Care")
    return st
  def __str__(self):
    print('This is apple product.')
  def calculatePrice(self):
    print('Total Price:', self.base_price)

class MacBookPro2020(AppleProduct):
  def __init__(self,name,model,ram,chip,tax,base_price=None):
    super().__init__(name,model,base_price)
    self.base_price=1299
    self.ram=ram
    self.chip=chip
    self.tax=tax

  def __str__(self):
    a=super().feature()
    print(a + f"RAM:{self.ram}\nChip:{self.chip}")
    b=super().companyInfo()
    return b
  def calculatePrice(self):
    self.total_tax=(self.base_price*self.tax)/100
    self.base_price+=self.total_tax
    print(f"Calculating Total Price:\nBase Price:{self.base_price}\nTax:{self.tax}% ")
    x=super().calculatePrice()
    return x
  def __add__(self,other):
    return self.base_price + other.base_price

class iPhone12(AppleProduct):
   def __init__(self,name,model,ram,chip,tax,base_price=None):
     super().__init__(name,model,base_price)
     self.base_price=799
     self.ram=ram
     self.chip=chip
     self.tax=tax
   def __str__(self):
    a=super().feature()
    print(a + f"RAM:{self.ram}\nChip:{self.chip}")
    b=super().companyInfo()
    return b
   def calculatePrice(self):
    self.total_tax=(self.base_price*self.tax)/100
    self.base_price+=self.total_tax
    print(f"Calculating Total Price:\nBase Price:{self.base_price}\nTax:{self.tax}% ")
    x=super().calculatePrice()
    return x

m1 = MacBookPro2020('MacBook', 'MacBookPro2020', 8, 'M1', 10)
print(m1)
print('====================================')
m1.calculatePrice()
print('###################################')
iphone = iPhone12('iPhone', 'iPhone 12', 8, 'A14', 5)
print(iphone)
print('====================================')
iphone.calculatePrice()
print('###################################')
print('Total Price of these two products: ',end='')
print('%.2f Dollars'%(m1 + iphone))

Name: MacBook
Product Model: MacBookPro2020
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple CareRAM:8
Chip:M1
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Calculating Total Price:
Base Price:1428.9
Tax:10%
Total Price: 1428.9
###################################
Name: iPhone
Product Model: iPhone 12
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple CareRAM:8
Chip:A14
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Calculating Total Price:
Base Price:838.95
Tax:5%
Total Price: 838.95
###################################
Total Price of these two products: 2267.85 Dollars

In [ ]:
#13
class University:
	name  = "ABC University"
	numberOfStudents = 0
	admissionFee = 28000
	Library = 2000
	def __init__(self, n,i):
    	self.stName = n
    	self.stId = i

	def payment(self):
    	return self.admissionFee + self.Library

	def __str__(self):
    	return "Student Name: {}, ID: {}\nFee: {}".format(self.stName, self.stId, self.payment())

# Write your codes here.
# Do not change the following lines of code.

c1 = CSE_dept("Mary","5678")
print(c1)
c1.payment_details()
print("===========================")
p1 = PHR_dept("Simon","91011")
print(p1)
p1.payment_details()
print("===========================")
c2 = CSE_dept("Adam","1234", 12)
print(c2)
c2.payment_details()
print("===========================")
p2 = PHR_dept("David","121314", 15)
print(p2)
p2.payment_details()
print("===========================")
print("Total Number of Students:", University.numberOfStudents)
print("Total University Revenue:", (c1 + c2) + (p1 + p2))
print("===========================")
print("Due to the pandemic, admission and library fees have been reduced for all departments. ")
University.admissionFee -= 1000
University.Library -= 100
print("The credit, semester and lab fees have been reduced for the CSE department. ")
CSE_dept.PerCreditFee -= 100
CSE_dept.SemesterFee -= 100
CSE_dept.LabFee -=100
print("The credit and semester fees have been reduced for the PHR department.\n ")
PHR_dept.PerCreditFee -= 100
PHR_dept.SemesterFee -= 1000
print(c1)
print(p1)
print(c2)
print(p2)
print("===========================")
print("Total Number of Students:", University.numberOfStudents)
print("Total University Revenue:", (c1 + c2) + (p1 + p2))

In [ ]:
#14
class Library:
    Total_book = 1000
    borrow_data = {}

    def __init__(self,n,id):
        self.student_name = n
        self.student_id = id

    def borrowbook(self):
        print("A book is borrowed!")

    def __str__(self):
        return "Library: XYZ"

#Write your code here
s1 = Student("Alice",18101259)
s1.borrowbook("The Alchemist", "Hdw652")
print("===============")
print(s1)
print("===============")
print(Library.borrow_data)
print("===============")
s1.borrowbook("Wuthering Heights")
print("===============")
print(s1)
print("===============")
s2= Student("David",18141777)
s2.borrowbook("The Alchemist", "Hdw652")
print("===============")
s2.borrowbook("The Vampyre")
print("===============")
print(Library.borrow_data)
print("===============")
s1.returnAllBooks()
print("===============")
print(Library.borrow_data)

In [ ]:
#15
class Player:
    database={}
    playerNo = 0
    def __init__(self,name,team,jerseyNo):
        self.name = name
        self.team = team
        self.jerseyNo = jerseyNo
    def __str__(self):
        return "Name:{}\nTeam:{}\nJersey No:{}".format(self.name,self.team,self.jerseyNo)

#Write your code here
class FootballPlayer(Player):
   def __init__(self,name,team,jerseyNo,goal,retire='Not yet retired'):
     super().__init__(name,team,jerseyNo)
     self.goal=goal
     self.retire=retire
     Player.playerNo += 1
     self.n=self.name.split(' ')
    #  print(self.n)
     self.id=str(Player.playerNo) + self.n[0][0] + self.n[1][0] + str(self.jerseyNo)
     Player.database[self.id]=[name,team,jerseyNo,goal,retire]
    #  print(self.id)


   def __str__(self):
     a=super().__str__()
     return f"Player ID:{self.id}\n{a}\nGoals Scored:{self.goal}\nRetirement date:{self.retire}"
   @classmethod
   def createPlayer(cls,name,team,jerseyNo,goal,retire):
     return cls(name,team,jerseyNo,goal,retire)

print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)
print("#################################")
p1 = FootballPlayer("Lionel Messi","Barcelona",10,231)
print("------Details of the player------")
print(p1)
print("#################################")
p2 = FootballPlayer("Cristiano Ronaldo","Juventus",7,215)
print("------Details of the player------")
print(p2)
print("#################################")
p3 = FootballPlayer.createPlayer("Miroslav Klose","Lazio",11, 71,"11 Aug,2014")
print("------Details of the player------")
print(p3)
print("#################################")
print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)

Number of players: 0
Player Database: {}
#################################
------Details of the player------
Player ID:1LM10
Name:Lionel Messi
Team:Barcelona
Jersey No:10
Goals Scored:231
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID:2CR7
Name:Cristiano Ronaldo
Team:Juventus
Jersey No:7
Goals Scored:215
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID:3MK11
Name:Miroslav Klose
Team:Lazio
Jersey No:11
Goals Scored:71
Retirement date:11 Aug,2014
#################################
Number of players: 3
Player Database: {'1LM10': ['Lionel Messi', 'Barcelona', 10, 231, 'Not yet retired'], '2CR7': ['Cristiano Ronaldo', 'Juventus', 7, 215, 'Not yet retired'], '3MK11': ['Miroslav Klose', 'Lazio', 11, 71, '11 Aug,2014']}

In [ ]:
#19
class A:
  temp = -5
  def __init__(self):
    self.sum = 0
    self.y = 0
    self.y = self.temp - 3
    self.sum = A.temp + 2
    A.temp -= 2
  def methodA(self, m ,n):
    x = 1
    A.temp += 1
    self.y = self.y + m + self.temp
    x = x + 1 + n
    self.sum = self.sum + x + self.y
    print(f"{x} {self.y} {self.sum}")

class B(A):
  x = -10
  def __init__(self, b = None):
    super().__init__()
    self.y = 4
    self.temp = -5
    self.sum = 2
    if b == None:
      self.y = self.temp + 3
      self.sum = 3 + self.temp + 3
      self.temp -= 2
    else:
      self.sum = b.sum
      B.x = b.x
      b.methodB(1,3)
  def methodA(self, m, n):
    x = 1
    self.temp += 1
    self.y = self.y + m + self.temp
    x = x + 7 + n
    super().methodA(x, m)
    self.sum = self.sum + x + self.y
    print(f"{x} {self.y} {self.sum}")
  def methodB(self, m, n):
    y = 3
    y = y + self.y
    B.x = self.y + 3 + self.temp
    self.methodA(B.x, y)
    self.sum = self.x + y + self.sum
    print(f"{B.x} {y} {self.sum}")


a1 = A()
b1 = B()
b2 = B(b1)
b1.methodA(3,2)
b2.methodB(1,2)

-4 -11 -14
9 -11 -16
-6 1 -21
5 -8 -24
10 -8 -22
4 13 18
15 13 46
2 7 55

In [ ]:
#final summer
class Monster:
  monsterCount=0
  def __init__(self,name,power):
    self.name=name
    self.power=power
    self.alive=True
    Monster.monsterCount += 1
  def get_details(self):
    return f'Name:{self.name}\nPower:{self.power}\nAlive:{self.alive}'

  def attack(self,*args):
    if len(args) == 0 :
      print('No monsters to attack')
    for i in args:
      if self.alive == True and i.alive == True:
        if self.power>i.power:
          print(f'Attack successful.{self.name} defeated {i.name}.')
          i.alive = False
          Monster.monsterCount -= 1
        else:
          print(f'{self.name} defeated {i.name}')
          Monster.monsterCount -= 1
      elif self.alive == True and i.alive == False:
        print(f"Cannot attack {i.name} \nIt's not alive.\nAttack unsuccessful.")
      elif self.alive == False:
        print(f'{self.name} is not alive to attack.')


monster1 = Monster('Godzilla', 40)
monster2 = Monster('Hydra', 30)
monster3 = Monster('KingKong', 50)
print(f"Number of monsters alive:{Monster.monsterCount}")
print('1--------------------------------')
print(monster1.get_details())
print('2--------------------------------')
print(monster2.get_details())
print('3--------------------------------')
print(monster3.get_details())
print('4--------------------------------')
monster1.attack()
print('5--------------------------------')
monster1.attack(monster2)
print('6--------------------------------')
monster1.attack(monster2, monster3)
print('7--------------------------------')
print(f"Number of monsters alive:{Monster.monsterCount}")
print('8--------------------------------')
print(monster2.get_details())
print('9--------------------------------')
monster2.attack(monster1)

Number of monsters alive:3
1--------------------------------
Name:Godzilla
Power:40
Alive:True
2--------------------------------
Name:Hydra
Power:30
Alive:True
3--------------------------------
Name:KingKong
Power:50
Alive:True
4--------------------------------
No monsters to attack
5--------------------------------
Attack successful.Godzilla defeated Hydra.
6--------------------------------
Cannot attack Hydra
It's not alive.
Attack unsuccessful.
Godzilla defeated KingKong
7--------------------------------
Number of monsters alive:1
8--------------------------------
Name:Hydra
Power:30
Alive:False
9--------------------------------
Hydra is not alive to attack.

In [ ]:
#final summer
class User:
    activities = ["Post", "Like", "Comment"]
    def __init__(self, name,email):
      self.name = name
      self.email = email

    def UserActivity(self, activityType):
       if activityType in User.activities:
           return True
       else:
           return False

    def userDetail(self):
        return f"User Detail:\nName:{self.name}\nEmail: {self.email}"
#Write your code here
class BracbookUser(User):
  def __init__(self,name,email,phone=None):
    super().__init__(name,email)
    self.phone=phone
    self.activity='No recent activity'
    self.acti=""

  def userDetail(self):
    a=super().userDetail()
    if self.phone == None:
      return a+f"\nPhone:Not set\nActivity Log:{self.activity}."
    else:
      return a+ f"\nPhone:{self.phone}\nActivity Log: {self.activity}."

  def UserActivity(self,act):
    self.act=act
    a=super().UserActivity(act)
    if a == True:
      self.acti += self.act+" "
      self.activity=self.acti
      print(f'{self.name} has {self.act}(d/ed) successfully.')
    else:
      print(f"No activities found like {self.act}")


user1 = BracbookUser("Rakait","xyz@gmail.com")
print("1===========================")
print(user1.userDetail())
print("2===========================")
user2 = BracbookUser("Sazzad","abc@gmail.com","01727xxxxxx")
print("3===========================")
print(user2.userDetail())
print("4===========================")
user1.UserActivity("Like")
print("5===========================")
user1.UserActivity("Comment")
print("6===========================")
print(user1.userDetail())
print("7===========================")
user2.UserActivity("Share")
print("8===========================")
user2.UserActivity("Comment")
print("9===========================")
print(user2.userDetail())

1===========================
User Detail:
Name:Rakait
Email: xyz@gmail.com
Phone:Not set
Activity Log:No recent activity.
2===========================
3===========================
User Detail:
Name:Sazzad
Email: abc@gmail.com
Phone:01727xxxxxx
Activity Log: No recent activity.
4===========================
Rakait has Like(d/ed) successfully.
5===========================
Rakait has Comment(d/ed) successfully.
6===========================
User Detail:
Name:Rakait
Email: xyz@gmail.com
Phone:Not set
Activity Log:Like Comment .
7===========================
No activities found like Share
8===========================
Sazzad has Comment(d/ed) successfully.
9===========================
User Detail:
Name:Sazzad
Email: abc@gmail.com
Phone:01727xxxxxx
Activity Log: Comment .

In [ ]:
class A:
  temp = 5
  def __init__(self):
    self.y = A.temp - 2
    self.sum = A.temp + 1
    A.temp += 3
  def methodA(self, m, n):
    x = 0
    self.y = self.y + m + (A.temp)
    x = x + 2 + n
    print(x, self.y, self.sum)
    self.methodB(-2, 6)
    self.sum = self.sum + x + A.temp
    self.methodB(-4, self.sum, 3)
  def methodB(self, m, n):
     y = 5
     y = y + self.y
     self.sum = B.x + y + n
     print(B.x, y, self.sum)
class B(A):
 x = 1
 def __init__(self, obj=None):
   super().__init__()
   if obj != None:
      obj.sum = 11
   self.y = A.temp + 4
   self.sum = 3 + A.temp + B.x
 def methodB(self, m, n, y=0):
     y = y + self.y + n
     B.x = m + self.y + n
     self.sum = B.x + y + A.temp
     print(B.x, y, self.sum)
b1=B()
b2=B(b1)
b1.methodA(-3,-7)

-5 20 11
24 26 61
83 90 184

In [ ]:
class Exam:
  def __init__(self,typ,q,marks):
    self.typ=typ
    self.q=q
    self.marks=marks
    self.total=0
  def detail(self):
    if self.typ == 'Midterm':
      self.total += 20
    else:
      self.total += 30
    return f'Exam Type:{self.typ}\nNumber of questions:{self.q}\nMarks per questions:{self.marks}\nTotal Marks:{self.total}'

e1 = Exam('Midterm', 2, 10)
print(e1.detail())
print("===========================")
e2 = Exam('Final', 3, 10)
print(e2.detail())

Exam Type:Midterm
Number of questions:2
Marks per questions:10
Total Marks:20
===========================
Exam Type:Final
Number of questions:3
Marks per questions:10
Total Marks:30

In [ ]:
oTV = RickMote()
oTV.power()
print("1.############################")
oTV.showInfo()
print("2.############################")
oTV.changeChannel()
oTV.changeVolumeLevel()
oTV.showInfo()
print("3.############################")
oTV.power()
oTV.showInfo()
print("4.############################")
oTV.power()
oTV.changeVolumeLevel(4)
oTV.changeChannel(3)
oTV.showInfo()
print("5.############################")
oTV.changeVolumeLevel(-2)
oTV.showInfo()
print("6.############################")
oTV.power()
oTV.changeChannel(9)
oTV.changeVolumeLevel(-1)
oTV.showInfo()
print("7.############################")
oTV.power()
oTV.changeChannel(11)
oTV.showInfo()

In [ ]:
#LAB FINAL
class FinalExam:
     def __init__(self, name):
         self.__name = name
     def setName(self, name):
         self.__name = name
     def getName(self):
         return self.__name
     def __str__(self):
         return self.__name
     def printDetails(self):
        return f'I wish there were no finals'
###Write your code here
class Student(FinalExam):
  total=0
  def __init__(self,name,id,dep):
    super().__init__(name)
    self.id=id
    self.dep=dep
    Student.total += 1
  # def __str__(self):
  #   a=super().__str__()
  #   return a
  def printDetails(self):
      print('Question khub easy!!!')
      print(f"Student Name:{FinalExam.self.__name},Id:{self.id},Department:{self.dep}")
      print("Kintu pass korte hole final exam to ditei hobe!!")
      print(f"Total number of Students:{Student.total}")


t1 = Student('Andy','18101201', 'CSE')
print(t1)
print(t1.printDetails())
print("=================================")
t2 = Student('George','19101311', 'CSE')
print(t2)
print(t2.printDetails())
print("=================================")
t3 = Student('Mina', '19201421', 'BBA')
print(t3)
print(t3.printDetails())
print("=================================")
t4 = Student('John', '18401221', 'BBA')
print("=================================")
# print(t1+t3)
# print("=================================")
# print(t1+t2)
# print("=================================")
# print(t2+t3)
# print("=================================")
# print(t2-t4)

Andy
Question khub easy!!!

AttributeError: ignored

In [ ]:
class A:
  x=5
  def __init__(self):
    self.x=100
class B(A):
  x=2
  def __init__(self):
    super().__init__()
b=B()
print(b.x)

100

In [ ]:
a=("CSE111",83.5,"CSE230",73.0,"CSE260",92.5)
l=len(a)
# print(l)
for i in range(1,l,2):
  c=a[i-1]
  m=a[i]
# print(i)
  print(c)

CSE111
CSE230
CSE260